bwinton/TabCenter

- bootstrap.js
- docs/metrics.md
- utils.js
- verticaltabs.jsm
@clouserw, @johngruen, @6a68: How does this all look to you?  Anything missing?  Anything wrong?
> Add metrics.

- .travis.yml
@bwinton
- will only run lint on master branch
- will run on push to master, and on PR to master
> add travis.yml, run lint as test

- verticaltabs.jsm
@bwinton 
- tabs only scroll if out of view
- will scroll to top if above top, will scroll to bottom if over bottom.
https://github.com/bwinton/VerticalTabs/issues/245
> only scroll if out of view, and attach to top or bottom depending on position

- verticaltabs.jsm
@bwinton 
New Tabs (from 'new tab' button or ctr-t) now open at top, then scroll into view
- #3
> move new tab to top of list

- skin/light/light.css
- Other CSS had overruled specificity - make it more specific
- re-fixes PR #231
> make css more specific - no margin on popups

- skin/light/light.css
- verticaltabs.jsm
> Fix: Don't show unidentified buttons in the tab's toolbar.

- CHANGELOG.md
docs: Add a changelog.  🌳🌲
[v1.20](https://github.com/bwinton/VerticalTabs/releases/tag/v1.20) was auto-generated from a package that I should push somewhere one of these days… 😉
The rest were arduously hand-copied from the [GitHub releases](https://github.com/bwinton/VerticalTabs/releases).
Fixes #298.
> Add a changelog!

- README.md
list on the README the add-ons that tab center does not play nice with.
fixes: #234.
> docs: add incompatibility notes 💔 

- Makefile
- bootstrap.js
- options.xul
- utils.js
- verticaltabs.jsm
@bwinton 
In add-on options page user can now toggle preference of opening new tabs at bottom or top. Top is set as default.
fixes: #322
> feature: set pref in options to change new tab opening locstion

- .stylelintrc.json
- package.json
- skin/light/light.css
- verticaltabs.jsm
Update stylelint to match the version in my editor.
Switch the width of the sidebar to use a css variable.
Add a splitter box, and adjust the css variable when it's moved.
Fixes #23.
Reviewed by @ericawright.
> fix: Make the pinned sidebar resizable.  ⟸║⟹   😃

- skin/base.css
Move the collapsed width to a variable so we can more easily change it.
Make it `60px` instead of `45px` to show the entire thumbnail.
Reviewer: @ericawright.
> fix: Make the collapsed-width a little bigger. 🖼

- skin/base.css
- skin/win.css
- verticaltabs.jsm
Add a border to the sidebar to distinguish it from page content.
Make the background colour of the active tab match the spec.
Add a border and box shadow to the meta image.
Show the dashed border image on missing images.
Add some padding.
Move the favicon down to the bottom of the thumbnail.
Only show the hostname for http(s) urls.
> fix: Various style fixes. 💅🏻

- verticaltabs.jsm
I'm not sure if this is correct, especially the part about setting the label twice.
r? @bwinton
> Hide wyciwyg:// uris

- vertical-tabbrowser.xml
- verticaltabs.jsm
r: @bwinton 
- Move getUri int VT prototype (for access to document)
- double click on tab-meta-image does not open a new tab
> Fix/thumbclick ⛵ 

- main.js
- package.json
- verticaltabs.js
> feat: Option to disable thumbnails.

- vertical-tabbrowser.xml
- verticaltabs.js
r: @bwinton 
- thumbnails update on redraw
- labels inherit value from parent
> fix: Disappearing labels

- skin/base.css
- verticaltabs.js
> fix: Take the sidebar into account when determining the autocomplete's place.

- vertical-tabbrowser.xml
As reported by @phlsa on Slack.
> fix: Handle retina devices in the thumbnails!

- .eslintrc.json
- skin/base.css
- skin/glyph-arrow-page-down-16.svg
- skin/glyph-arrow-page-down-inverted-16.svg
- skin/glyph-arrow-page-up-16.svg
- skin/glyph-arrow-page-up-inverted-16.svg
- skin/linux.css
- skin/osx.css
- skin/win.css
- vertical-tabbrowser.xml
- verticaltabs.js
r: @bwinton 
- can drag and scroll tabs when there are enough for a scrollbox
Fixes: #494.
Fixes #500.
> feature: scroll tabbrowser when dragging a tab 📜 📑 

- main.js
> Don't conflict with the devtools keys.

- skin/win.css
> Style: remove left border from win 8 and 7

- skin/base.css
> fix: Find icon stays in place even when searching with long strings

- verticaltabs.js
Override addTab method, move new tab and linked tab according to user pref.
fixes: #410.
fixes #462.
> Feature: links open above or below selected tab

- verticaltabs.js
r: @bwinton 
Add timeout to mouseleave `exit` event to fix #572 in an alternate way. 
Also lets user correct position if they overshoot.
fixes: #572 (again).
> fix: Paste into find-input

- skin/base.css
- skin/linux.css
- skin/osx.css
- skin/win.css
r: @bwinton 
remove display: flex
style to center content
fixes: #612
> fix: Keep search context menu open in windows

- verticaltabs.js
r: @bwinton 
change focus to first unpinned tab on startup
fixes: #605
> fix: Start page looses focus with pinned tabs

- main.js
- verticaltabs.js
r: @bwinton
🎵 there once was a key that didn't crop
but then that behavior did stop
stats send without clicker
and the time opens quicker
please give it a test on your laptop 🎵 
(add crop when opening with hotkey
send stats when opening with crop.
stop stats from sending when mousing in after hotkey opens
shorten timeout to 300ms from 500ms)
fixes: #637 
fixes: #633
> fix: add crop when opening with hotkey

- package.json
- verticaltabs.js
r: @bwinton 
- change tabs to open on the bottom by default
- change the drawer to be pinned open by default
> feature: Change Defaults

- verticaltabs.js
r: @bwinton 
- set leftbox `expanded` by default to allow crop 
(this also should not have affected current users.... curious)
fixes: #656
> fix: allow crop

- verticaltabs.js
r: @bwinton
crop was not actually fixed 😨 but now it is 😄 
to test: 
- open nightly with "show tabs from last time" enabled.
- install using xpi file
- unpin TC
- reopen nightly
ER: uncropped tabs to allow a few letters to peak
AR: cropped tabs, cannot see any letters
> fix: clean up crop, remove crop mutation listener

- skin/base.css
> fix: allow light colored expand icon in dev theme

- verticaltabs.js
> refactor: remove old metadata option for tab previews

- verticaltabs.js
> fix: allow autocomplete to expand to full width in windows fullscreen

- verticaltabs.js
r= @bwinton  
- init with overflow true to allow for proper tabbing and scrolling
fixes: #698.
> fix: initial tab scrolling

- skin/base.css
- verticaltabs.js
r: @bwinton 
note: only relevant for windows. edit: and Linux
fixes: 721
> fix: hide tab center in print preview mode

- verticaltabs.js
r: @bwinton
right click on pin_button doesn't pin/unpin
fixes:  #472
> fix: right click on pin icon pins/unpins

- verticaltabs.js
r: @bwinton
force pinned width to be half of window size, or less, when resizing the window
fixes: #604
> fix: pinned width changes on resize

- verticaltabs.js
> fix: init pin-button with "shrink" tooltip

- verticaltabs.js
@bwinton 
- for installs/uninstalls, toggle top mode, and customization changes
fixes: #739
> fix: restore urlbar value

- verticaltabs.js
> fix: visible tabs null on changing groups

- verticaltabs.js
> fix: typo, and change to array for filter

- verticaltabs.js
@bwinton
set initial pin-button toolbartext value according to pinned state
fixes: #751
> fix: pin-button dynamic tooltiptext 

- verticaltabs.js
@bwinton
when opentabstop pref is true, tabs close above, not below
> Fix: change close label to reflect behaviour

- verticaltabs.js
@bwinton
remove popuphidden event listener on unload
> fix: remove popuphidden event listener on unload

- .gitignore
- .jpmignore
- genlocales
- get-locale-strings.js
- locale/README.md
- locales/README.md
- locales/en-US/addon.properties
- main.js
- package.json
- verticaltabs.js
Going through all the code is a pain, but I think it's way better this way.  🙂
Fixes #360.
> First cut at l10n.

- main.js
@bwinton 
restore toggledon, tabspinned, and tabspinnedwidth attributes per window
fixes: #528
fixes: #391 
fixes: #431
> feature: restore persistant attributes per window

- skin/base.css
- verticaltabs.js
@bwinton 
send the right thing to PrintPreviewListener, also, fully expand preview page when TC in shrink mode
It's possible that this fixes all the PrintPreview things :)
fixes: #791.
fixes: #792.
> fix: print preview

- verticaltabs.js
@bwinton 
remove extra #newtab-popup that were causing small squares to appear
Fixes: #600.
> Fix: Strange Squares ◽️ ◾️ ◽️ ◾️ 

- vertical-tabbrowser.xml
- verticaltabs.js
@bwinton
fixes scroll on windows when reversed, and scroll with pinned tabs
- please test on win/linux with trackpad
- and with mouse scrollwheel (on all stsyems)
> fix: reversed scroll

- main.js
- verticaltabs.js
> fix: restore each window session on windows and linux

- verticaltabs.js
> interpolate correctly for shrink and expand strings

- main.js
> remove search hanger from the tour

- main.js
> tour bubble can only be closed by actively dismissing it.

- skin/persistant.css
> remove border on button from windows

- verticaltabs.js
> fix: splitter only accepts left clicks

- vertical-tabbrowser.xml
remove reference to method calling an error in nightly
@bwinton
> fix:updateWindowResizers

- docs/metrics.md
- main.js
- utils.js
> send metrics to track tour interactions

- main.js
- skin/base.css
- vertical-tabbrowser.xml
- verticaltabs.js
@bwinton 
fixes: #880 
fixes: #888 
fixes: #879 
fixes: #817
fixes: #881 
todo: test on linux and win
-----------------
~~known issues: when changing top and side tabs the pinned tabs sometimes change order~~
> Rework pinned tabs

- verticaltabs.js
> Fix: don't allow tabs opened from pinned tabs to open above them

- verticaltabs.js
Add missing `.VerticalTabs` property access to fix Toolbar customization.
> fix: Toolbar customization.

- main.js
- verticaltabs.js
- for shield only, start all windows tabs on top
Fixes #930.
> feature: init all windows tabs on top for shield

- main.js
- verticaltabs.js
check against 'true' to hopefully minimize errors
> Fix: always check toggledon attribute against 'true'

- verticaltabs.js
- reset visible tabs when a new one opens so it is included in search
Fixes: #1004
> fix: New tabs are not filtered in search

- docs/metrics.md
- main.js
- utils.js
> fix: Send ping when hotkey used to focus and unfocus search.

- genlocales
Fixes: https://github.com/bwinton/TabCenter/issues/992.
> fix: Add en-locale for those who are not set to en-US

- main.js
- skin/base.css
- verticaltabs.js
show search all the way until the tab bar is too thin for it.
Kind of fixes: #975.
> fix: Search stays visible until impossible

- main.js
- skin/base.css
- verticaltabs.js
@bwinton my VMs are acting up and I can't test this at all - I believe this should fix the first of the two F11 issues. Will check once I'm on my other computer, but if you'd like to check on windows that would be great too. 
https://github.com/bwinton/TabCenter/issues/951
https://github.com/bwinton/TabCenter/issues/952
> fix: F11 fullscreen and toggle

- locales/sl/addon.properties
update l10 before pushing new release
> update l10n 

- verticaltabs.js
tab does not disappear when user chooses to stay on page after confirmation
fixes: #1077.
> fix: 'Stay on Page' confirmation dialogue

- README.md
It's mentioned in the change notes but not the README. It is probably a good place to include it.
Thanks for making a great add-on, I miss it already.
> Mention TabCenter is EOL in README

- verticaltabs.js
> fix: Unpined tab does not jump to the top in reverse tabs.
