- bootstrap.js
- skin/light/light.css
- verticaltabs.jsm
so that we can set the right colours! 🙌🏻🙌🏼🙌🏽🙌🏾🙌🏿  Then we can just use `#TabsToolbar[brighttext]` instead of trying to figure out whether we're in the devtools dark theme or not!
reviewer: @ericawright 
- Replace the inferFromText method on the toolbar.
- Change the devtools dark theme to all dark themes.
- Fixes #132.
- Tested in Release with default, dark, and light themes, as well as DevEdition with default, dark, light, and devedition themes (with dark and light devtools modes).
> Replace the inferFromText method on the toolbar,

- verticaltabs.jsm
- to allow onunload trigger to resolve before animating the tab closed, changed removeTab to _endRemoveTab
fixes:  #317
> change removeTab to _endRemoveTab

- vertical-tabbrowser.xml
fix: Remove the white bar from the titlebar.  📶
Call `TabsInTitlebar.init();` to recalculate the titlebar size.
Fixes #319.
> Port @gijsk's fix from jdashg#10.

- docs/metrics.md
- utils.js
Reviewer: @pdehaan
fix: Don't double-wrap the telemetry ping.  📞🏡
Turns out the Test Pilot add-on will wrap the pings for us, so we don't need to include a bunch of the stuff we were doing.  The docs were also updated.
Fixes #327.
> Update the telemetry ping to not nest our payload.

- skin/light/light.css
fix: bottom tab being cut off ✂️ 
- remove extra 22px height from .tabbrowser-arrowscrollbox to account for lightweight themes
- remove 1px height from  .tabbrowser-arrowscrollbox that is visible in certain themes (on mac)
- custom rule for windows to remain at 42px always
fixes: #238
> fix: bottom tab being cut off

- skin/light/light.css
show the .tab-icon-overlay if muted, but no sound playing.
fixes: #323.
> fix: show muted icon if no sound playing. 🙊 

- verticaltabs.jsm
:scroll:
Use mutation to trigger scroll to tab, instead of tabSelect event, as that was happening before the tab would be moved and renamed. 
fixes: #338.
> fix: reopening a tab scrolls to it 

- verticaltabs.jsm
add listener and remove animating class once first animation is finished. 
refactor: don't add a listener on every new tab created, add to window instead. 😊 
fixes: #326 
**Notes:**
let me know if you want the refactor in a separate PR
> fix: remove slide-in animation from dragging tabs 🐉 📑 

- skin/light/light.css
**open for visibility** (there are still more bits to tidy)
remove padding from #TabsToolBar.
set #TabsToolBar height to align better with #appcontent.
remove unnecessary scroll bar in win 7, 8, 10.
remove clear border under #TabsToolBar in themes. 
fixes: #88. 
fixes: #169.
> Style: windows edits 👸 

- verticaltabs.jsm
Call resizeTabs after deleting a tab, not before.
Reviewer: @bwinton
> fix:resize on deleting a tab

- skin/base.css
Add a maximum width for the splitter, too.
Fixes #414.
> fix: Make sure the splitter doesn’t grow too large.  🐞

- verticaltabs.jsm
r: @bwinton 
restore #navigator-toolbox children to receive brighttext attr
fixes: #305.
> fix: toolbar icons correctly change color in dark themes

- verticaltabs.jsm
r: @bwinton 
on clicking on the find icon focus the find bar.
fixes #420.
> fix: click on find icon 🌁 

- verticaltabs.jsm
Use `PageThumbs` instead of `BackgroundPageThumbs`.
Also store the url where we can for ease of reading. 😉
Reviewer: @ericawright.
Fixes #427.
> fix: Use a better API for thumbnail loading.

- skin/base.css
r: @bwinton 
When in fullscreen, the pinned TC no longer shows.
Fixes: #441.
> fix: Hide splitter when in fullscreen

- skin/base.css
r: @bwinton 
- hide private browsing indicator when inside of the #verticaltabs-box, for now.
fixes: #502. (sort-of)
note: private browsing indicator is still visible on mac as it is not located inside of #verticaltabs-box. But it looks good in the top right corner of the #titlebar
> fix: hide private browsing icon :mask:

- verticaltabs.js
Tabs will never be resized if the mouse is in the tab area.
When the mouse leaves the tab area, tabs will be resized after a short delay.
r? @bwinton
> Introduce delay before resizing tabs (fixes #465)

- main.js
- package.json
- skin/base.css
- vertical-tabbrowser.xml
- verticaltabs.js
Bail on updating stuff if we don't have a linkedBrowser yet.
Don't add two VerticalTabs instances to a window.
Watch for the `domwindowopened` event to catch all opening windows.
Mark the add-on as multiprocess-compatible.
Fixes #529.
> fix: Run the initialization code for _all_ the new windows.

- main.js
- skin/base.css
- verticaltabs.js
Used `ctrl-shift-k`/`cmd-shift-k` to be like the searchbar.
Needed to add the extra attribute so that we would do sane things when the mouse was or wasn't in the sidebar when toggling.
Fixes #95.
> fix: Add a hotkey to toggle focus the tab searchbox.  🔥

- skin/base.css
style overflow:hidden on search-input
Fixes: #573.
> Style: search box does not overflow 

- verticaltabs.js
reviewer @bwinton
remove scroll method in favor of built-in arrowscrollbox method. 
restore overflow attribute in order to use said method.
Fixes: #273.
Fixes: #492.
> Fix: rough scroll on expanded

- verticaltabs.js
- disable options to "Move to Menu" and "Remove from Toolbar" from the new tab button
- find the new-tab-button if located inside customization-container or panel, and rebuild it in toolbar.
- put button back after
Fixes: #471.
Fixes: #554. (hopefully)
> Fix:Rebuild newtab button

- skin/base.css
- vertical-tabbrowser.xml
Use an actual element for the pin icon, for better positioning.
Fixes #557.
> fix: Don't let the pin icon overlap the thumbnail/favicon.

- skin/base.css
- verticaltabs.js
Move the delay from CSS to JavaScript, so that we can more easily control it.
Then use a setTimeout to add the delay.  And don't forget to clear it!
Fixes #331.
> fix: Snap open the sidebar when the cursor is slammed all the way left.

- vertical-tabbrowser.xml
Use the built-in this._scrollButtonUp/Down fields.
Reset the overflow according to what the height is, instead of trusting the event.
To be landed after #586… 😉
(I've been adding the ready label for patches that are reviewed, but waiting to land.)
Fixes #549.
> fix: Fewer arrows. 🏹🏹🏹

- vertical-tabbrowser.xml
Look for `ondragexit` instead of `ondragleave`, since apparently `ondragleave` doesn't get called.  ¯\_(ツ)_/¯
Fixes #548.
> fix: Stop auto-scrolling forever when dragging over an arrow button…  ⏳

- verticaltabs.js
@bwinton 
Hide the window controls if they were moved to the TabsToolbar. 
Move the fullscr-toggler to be above the main window, instead of above tab center
notes: currently adding window controls to the #nav-bar. would like to add to the #titlebar but it will not work with the slide in out/toggle on mousing up.
Fixes: #509.
> Fix: window controls in fullscreen

- vertical-tabbrowser.xml
Okay, this seems to work…
I'm not entirely sure why, but checking the container seems to yield better results.
Tested on Windows and Mac.
> fix: Uh, actually fix the arrows on overflow. 🙄

- verticaltabs.js
r: @bwinton 
keep TC expanded when related context menus are open.
Note: With this strategy, it and the context menus will stay open until the context menu is closed. Whether being hovered or not.
fixes: #572.
fixes: #470.
> fix: keep expanded on hover for context menus

- verticaltabs.js
check the target attribute rather than the newValue
fixes:
when cmd-tab  through tabs with TC permanently expanded the tab would not scroll into view.
> fix: tab scroll on expanded

- verticaltabs.js
r: @bwinton 
Don't catch close events from tooltips.
Skip the first call to `exit` from the find-input context menu.
fixes: #572.
> fix: Allow pasting into find-input when unpinned

- verticaltabs.js
r: @bwinton 
when removing a tab change focus before animating out :D
fixes: #306.
> fix: Delete tabs without waiting for animation to finish 🐎 🏁

- vertical-tabbrowser.xml
- verticaltabs.js
r: @bwinton 
When tab count gets reduced to amount where large tabs show, load all thumbs one time.
Only load thumbs on new tabs if parent has class 'large-tabs'.
fixes: #607. (at least partially)
> fix: Only load thumbnails when tabs are large

- verticaltabs.js
r: @bwinton 
call `clearFind` on creating a new tab.
fixes: #620
> fix: Clear search filter on new tab

- verticaltabs.js
Don't register clicks on the leftbar if it's not open.
Fixes #200.
> fix: Handle touch support in a nicer way.

- skin/base.css
r: @bwinton 
fixes: https://github.com/bwinton/TabCenter/issues/566
was happening due to this `background-image`:
> style: remove gradient from dark dev edition theme

- skin/base.css
- verticaltabs.js
r: @bwinton
- for Windows and Linux tabs will now tuck out of the way for F11 fullscreen
- for Mac, awesome bar will not hide in fullscreen
fixes: #660
fixes: #307 
fixes: #642
> fix: hide in fullscreen

- main.js
- verticaltabs.js
r: @bwinton 
- search is no longer cleared on mouse out when drawer remains open from hotkey toggle
- search is cleared when hotkey toggle closes drawer
fixes: #663
> fix: don't clear search on mouse out when open

- package.json
r: @bwinton 
this was changed previously due to misunderstanding
*sorry to those who will be surprised... again*
> fix: default tabs to open at the bottom

- verticaltabs.js
r: @bwinton 
center click and ctrl-click link from pinned tab does not change focus
fixes: #672
> fix: link from pinned tab does not change focus

- skin/osx.css
r:@bwinton
remove bottom margin from toolbar on mac (you could see it at the top of the scrollbar)
> style: remove bottom margin from toolbar

- main.js
- skin/base.css
- skin/linux.css
- skin/osx.css
- skin/win.css
- utils.js
Summary of changes:
- Change how TabCenter CSS is loaded
Before this PR, everything TabCenter sets with CSS is more important than everything else (on top of the chain). Now, TabCenter just follows the normal rules of CSS priority. This simple change allows customization-savy users to override everything else, while still giving importance to TabCenter's CSS.
- Clean up TabCenter CSS
Removed redundant rules, invalid selectors (that were previously simply ignored).
The gradient that TabCenter removes in https://github.com/bwinton/TabCenter/commit/446c3fd1fefbb7a4f97ae6a8e2360520efe887b7 is actually from https://github.com/bwinton/TabCenter/blob/master/skin/osx.css#L85
I've fixed that redundancy as well.
> Change how TabCenter CSS is loaded & Clean up TabCenter CSS

- skin/base.css
> hide TC in windows fullscreen with sidebar open

- skin/base.css
- verticaltabs.js
r: @bwinton
- on mouse out and mouse in, scroll will stay in the same position.
fixes: #669
> fix: on change of overflow, keep scroll position the same

- verticaltabs.js
r= @bwinton 
- save the first tab label so it does not become "new tab" on disable
fixes: #564.
> fix: first tab title becomes "new tab"

- verticaltabs.js
r: @bwinton 
- Make `filtertabs` Tab Groups compatible
- Resize tabs according to the visible tabs, not all (only testable in test pilot version)
- `clearFind` or removing a tab
- `clearFind` on changing tab groups
fixes: #692
> fix: filter only through visible tabs

- main.js
- utils.js
- verticaltabs.js
Don't send the ping on shutdown, or every 24 hours, but instead send one per-event.
@clouserw Two questions…
1. I'm sending the `tab_center_tabs_on_top` and (new) `tab_center_show_thumbnails` prefs on every ping.  Does that seem reasonable to you?  Should we only send them sometimes?
1. Should we add a little more telemetry to see how often people use the search bar and how often people see the thumbnails (vs. just the favicons)?
Reviewer: @chuckharmiston
> fix: Re-work the Telemetry ping.  🎧

- verticaltabs.js
r: @bwinton 
(oops)
only clear visibletabs if using tab groups to switch
when pressing esc, or clicking the placeholder tab to clear the search, all tabs would disappear.
> fix: clearSearch

- vertical-tabbrowser.xml
- verticaltabs.js
r: @bwinton 
selected tab does not scroll into view on mouse out nor in.
selected tab does not scroll into view on resizing pinned size. (test by resizing really small)
tabs opened by ctrl-click are scrolled into view if it does not scroll off the selected tab
fixes: #730
> fix: do not scroll selected tab into view on mouse out/in

- verticaltabs.js
r: @bwinton 
fixes: #733 
note: @Quicksaver the version you just released has code which is overriding the `filtertabs` method, this seems to cause the temporary tab (that appears while filtering) to stick around when switching groups
> separate tabactions and tabgroupchange in clearfind

- skin/base.css
@bwinton 
input box must be 20px smaller because of icon
fixes: #743
> fix: search input overflow

- main.js
- utils.js
- verticaltabs.js
open for visibility
r: @bwinton 
- attach a window id to each window
- send toggle-on and off events
- send other events when toggled off (create tab, pin tab etc)
todo: 
- send current toggled state of window
questions: 
- what good does the window id do for us? It may be useful if we knew what other windows were open and their toggled states. Each ping is per-window anyway though, so currently does not serve a purpose
> send ping on toggle, save id per window

- verticaltabs.js
@bwinton 
Saw this bug on @phlsa 's machine. It is only replicate-able rarely ( I have not been able to). When clicking to toggle top tabs, nothing happens.
`tab.label is undefined, line 852` was in the console.
> fix: check for tab.label before trying to match

- verticaltabs.js
@bwinton 
#747 automatically hid the tab if the label was not ready in time. whoops.
> fix: don't allow tab to be hidden if there is no label

- verticaltabs.js
@bwinton 
remove mouseInside attribute when toggling to top tabs so TC will expand on entering
Fixes: #759
> fix: Mouse enter after toggle

- skin/base.css
- skin/osx.css
- verticaltabs.js
@bwinton 
- when changing themes, or toggling top tabs dark theme would not activate until changing focus away from firefox.
- return the slight opacity on the toolbars, remove the gradient.
Fixes: #476
> fix: Theme Changes in Win and Linux

- skin/base.css
- verticaltabs.js
@bwinton
tabs do not animate on togling top/bottom, nor after full screen, nor on opening new window
Fixes: #758
> fix: Cleaner Animations

- vertical-tabbrowser.xml
- verticaltabs.js
@bwinton 
to allow wheel scrolling when tabs are reveresed, set arrowscrollbox. _isRTLScrollbox depending on opentabstop pref
fixes: #776
> fix: reversed mouse-wheel scrolling

- verticaltabs.js
@bwinton 
scroll to active tab on startup, like browser default
fixes: #738.
fixes: #693.
> fix: scroll jump to top of tab list

- main.js
@bwinton 
For users who have `tabsontop` pref enabled, now that we are switching how we handle it, do not surprise them by reversing their tabs on upgrades.
fixes: #780
> fix: upgrade will not reverse tabs

- verticaltabs.js
@bwinton 
fixes the error caused by https://github.com/bwinton/TabCenter/commit/cc3694b172459f5222e0bfabbad13982af33811c 
tabs were not resizing on adding or removing tabs.
> resize tabs on initing a tab

- main.js
@bwinton 
Restore Windows and linux persistent attributes back to previous behavior
fixes: #818 
Note: currently does not remember on a per window basis like Mac does.
> restore persistant attributes for win and linux (not per window yet)

- vertical-tabbrowser.xml
@bwinton
if tabs are reversed, trigger opposite buttons scroll event on drag and scroll.
Fixes: #841.
Fixes: #826.
> fix: drag & scroll on reversed tabs

- verticaltabs.js
The `skipNextScroll` workaround for #730 is only necessary when the
sidebar is set to automatically shrink, otherwise in some cases we end
up with `skipNextScroll` set to true after exiting the sidebar. This
means that the sidebar won't scroll to display the next tab opened, see
#851 for more details.
This commit fixes this by only setting `skipNextScroll` to true if we
are in shrink mode.
Fixes #851
> fix: Scroll to open tab correctly after exiting the tab column

- verticaltabs.js
During session restore, the tabs get resized, and hence refreshed, every time a new tab is added. This patch changes things so we always delay the resize at least until the next turn of the event loop, thus merging all requests in the current turn. For my session with ~530 tabs, that saves about 90 seconds of session restore time.
> Merge all tab resize requests in an event loop turn

- verticaltabs.js
Following pull-request fixes two compatibility issues that prevented using Tab Center together with Toolbar Position Changer.
Fix 1. Use navbar parent node for insertBefore
Fixes compatibility issue with Toolbar Position Changer that enables to
move toolbars. Tab Center expects nav-bar to be child of navigation-toolbox.
This fix uses the parentNode of navbar element for determining the "real"
parent.
Fix 2.  Restore browser-bottombox location before customize
This fixes compatibility issue with Toolbar Position Changer add-on that
enables to move toolbars. TPC uses browser-bottombox as "bottom" toolbox
container for toolbars. Tab Center  moves bottombox to different location
which is not used by Firefox when entering to the Customize mode. This fix
restores the original position of …
> Fix compatibility with Toolbar Position Changer add-on

- main.js
- verticaltabs.js
stop infinite loop when all tabs pinned, put pinned tabs at the front of the tab strip when reversed.
Fixes #927
> Fix: pinned tabs stay to the left when on top.

- verticaltabs.js
r= @ bwinton
overrride getTabsToTheEndFrom to not count pinned tabs, so that context item gets disabled. And stops then from being counted/ closed when selecting a few tabs below the pins.
Fixes #928.
> Fix: pinned tabs get closed from 'Close Tabs Above' context option

- verticaltabs.js
r= @bwinton 
Reset `activeTab` after changing `vertical` attribute so it does not change when switching between top and side tabs
Fixes #849.
> Fix: toggle top/side tabs focuses wrong tab

- verticaltabs.js
r=@bwinton
- make numPinnedTabs a method on TC, 
- override `warnAboutClosingTabs` to…check properly for numpinnedtabs
Fixes #937.
Note: I'm sad that we can't use the binding to overrride tabbrowser - our verticalTabs.js file is getting out of control
> Fix: "Close Other Tabs" confirmation dialog

- verticaltabs.js
the issue is described in https://github.com/bwinton/TabCenter/issues/583#issuecomment-280907382
and it should restore the controllers of PlacesToolbar somehow.
here's dirty workaround that restores controllers manually, by performing `PlacesViewBase` constructor partially.
> Restore Places controllers after rearranging navigator-toolbox (fix #583)

- get-locale-strings.js
- locales/en-US/addon.properties
- main.js
- skin/persistant.css
Currently the page it points to is blank, but it will eventually be filled with info explaining the study.
This is only for shield and not for master.
Also, probably does not need to be translated, but to follow similar convention I added it in the same way as other strings.
> feature: open tab with more info on shield from last tour panel

- .jpmignore
- main.js
- package.json
- shield-config.js
- skin/persistant.css
- utils.js
Use shield cli to randomly assign control group or enabled group
- send metrics to testpilot telemetry and shield telemetry with `report`
- a little bit of css fixup to please the linter
TODO: 
- eliminate users of tabcenter and other tab related addons. 
- decide how many days the study will run for, currently set at 14
> Feature: shield telemetry and randomization

- docs/metrics.md
- utils.js
r=@bwinton
r=@ncloudioj
r=@clouserw
Add mandatory field event_type and rewrite metrics.md
I'm not entirely certain that the current state of the metrics is acceptable, if I could get a general look over that would be fantastic.
Fixes #939.
> Fix: missing event_type field

- main.js
- package.json
- shield-config.js
- utils.js
- unload cleanup
- small tabs and default versions
- don't install if certain add-ons are already installed.
~~@gregglind I was unable to test the shield study with an existing portfolio and so couldn't actually test the `isEligible` function. Instead I just tested the code in other places to have a sense of certainty that it would work. If you have a way of doing that please let me know.~~
I have tested `isEligible` by forcing `activeAddonIds` to contain some ids from `INCOMPATIBLE_ADDONS`. Note the function inside of `AddonManager.getAllAddons` will not run if no addons are installed, so must also remove this in order to test.
> feature: cleanup after unload, excluded addons

- verticaltabs.js
- tabs are opened in correct positions when opened from another tab (ctrl/cmd click)
Fixes https://github.com/bwinton/TabCenter/issues/956.
> fix: tabs are opened in correct positions in reverse

- vertical-tabbrowser.xml
We cannot test TC on release until it after the addon is signed. Theoretically I believe this should work.
I have tested this by overriding the method with the change in release on mac and Ubuntu, and both work.
> Fix: reverse inside _elementFromPoint

- verticaltabs.js
- set lastRelatedTab to be the created tab after it moves.
(turns out this was necessary)
Fixes: #996.
> fix: Child tabs open in correct position (reverse and pinned set).

- skin/base.css
The addition would allow for compatibility with testpilot-containers[1] #405 as detailed by @fvsch.
[1]: https://github.com/mozilla/testpilot-containers/issues/354
> Adding container CSS for highlight color change

- main.js
- verticaltabs.js
- do not reverse pinned tabs on startup (when tabs are reversed)
- also fixed: if fresh install, but user had previously used it and left it set to tabs on side, an error is thrown when the tour cannot find it's anchor.
Fixes: #1012.
> fix: Pinned tabs are reversed on browser restart

- verticaltabs.js
Trigger clearFind before unloading to ensure all tabs are recorded properly when unloading
Fixes: https://github.com/bwinton/TabCenter/issues/1015.
> fix: Tabs are permanently destroyed when filtered and browser closes 

- main.js
- verticaltabs.js
clearFind on shutdown as well as uninstall/remove
Fixes #1015.
> fix: Tab filtering and browser restart

- main.js
Lets try once more
clearFind on individual window close events
Fixes https://github.com/bwinton/TabCenter/issues/1015.
> fix: clearFind on individual window close events

- verticaltabs.js
Fix many search bugs. Also, show previously filtered tabs if the last visible tab closes.
Fixes #1043.
Fixes #1045.
Fixes #1044.
Fixes #1046.
Fixes #999.
Fixes #1040.
- ~~double-check that it is still compatible with Tab Groups~~ (yes, minus a little bug)
> Fix: add custom attribute to the filtered out tabs to keep track

- skin/base.css
- vertical-tabbrowser.xml
- verticaltabs.js
notes: using tab-highlight colour as background on active tab in compact themes - this looks a little funny, but better than not seeing anything at all. bonus, they will be fun colours if the user has containers.
in nightly, we still see the spinning box, but now also with a spinner inside.
Fixes #1038.
> Fix: show spinners in various versions and make visible in compact themes

- README.md
Mozilla Labs: Prospector - LessChrome HD is unable to show the url bar with 'ctrl+l' or by hovering near the top of the window. The navigation bar appears to work its just hidden slightly above the screen.
> Note an issue with LessChrome HD

- verticaltabs.js
ensure removeTab always calls our endRemoveTab
Fixes: #1062.
> fix: closing tabs on nightly leaves space and crashes

- main.js
- package.json
- verticaltabs.js
undo custom unpin code from before. 
remove reverse tabs pref as it causes too many complications to maintain and is irrelevant for the upcoming study.
(the code to support it remains if we decide to put it back in the future)
> fix:  Undo custom unpin code. remove reverse tabs pref
